spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/fullmall_pms

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
#      自增主键
      id-type: auto
server:
  port: 10000